language: python
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  firefox: latest
env:
  global:
    - PGPORT=5433
    - MOZ_HEADLESS=1
python:
- '3.5'
- '3.6'
services:
- postgresql
before_install:
- pip install --upgrade pip
- sudo service postgresql stop && sudo service postgresql start 10
install:
- pip install -r requirements.txt
- ./installgeckodriver.sh
before_script:
- psql -c 'drop database if exists eia' -U postgres
- psql -c 'drop role if exists eia' -U postgres
- psql -c 'create role eia' -U postgres
- psql -c 'create database eia' -U postgres
- psql -c "alter user eia with encrypted password 'eiae123';" -U postgres
- psql -c "alter role eia set client_encoding to 'utf8';" -U postgres
- psql -c "alter role eia set default_transaction_isolation to 'read committed';" -U postgres
- psql -c "alter role eia set timezone to 'utc';" -U postgres
- psql -c "alter role eia createdb;" -U postgres
- psql -c "grant all privileges on database eia to eia ;" -U postgres
script:
- ./test.sh
notifications:
  email:
  - 13-11223@usb.ve
  - 14-10955@usb.ve
  - ritces.parra@gmail.com
  - 14-10924@usb.ve
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: D9S6nbXTjkjva2J8Khc5ZIISpOxV1IYOVT0COeTCJC1puQQAPBdfz8pcepn9iusaVLVpxXsFtPZwxdckIu0ssAPOWoU4i3MufQK7XA6dW+dvyf3H9Gdt0Ae8uAzrbixAz2/lfKSShNZUZDPwtVCMB9eDWRJ6qllzxLb+AUqtT9x6wwJJTfC5mVImfpp9fgc5ZOsCzXFFeXvFrC9tpNhzuh3mWcJYk8PM9dhvqFE0j6FNqSv9bqKAvpfZ2WhKYlNc/14ulfDQyJydZ3va1Pgp1LPWpzYIMms4TfcGgwicl0lbpXgSVCBwSiwEXG7QF3GOr0prdupj2PSKZHKCX0nbCjih5HgESWXcV8+MPMYVaFfsEXV0n5A9yUzoPITtycIzRkj6R+AP0wGyPMwvKyza9Lfu9+QKI4/wh84WYuZJ627huoCloPPlZ3RhUvnF462Qwngtx3ay7KMVQhXLBN8Uz+c1GYIWJPzUT2B1lWXYK53RsYevqq9ynM5BHN2AWTc9tVDJNJOtfXoyKgOp+3icxuAMVQVckNNJNkiUzAjJc6k934ZCp9IXB1QrUcXonPnrg+UBq02hey5NplCycZR/1WiJHKe3t83x7+jnC3RYySS0RtlWpIsblRnVffVztnIQLEy3ib3BDGJkRDPWehRDgq9SYvIKVFPIZcUNWgxlHKw=
  app: eia-ci4712
  on:
    repo: german1608/EIA_CI4712
    python: '3.6'
